plugins {
	id 'java'
	id 'org.springframework.boot' version '2.7.18' 
	id 'io.spring.dependency-management' version '1.1.0'
}

group = 'com.example'
version = '0.0.1-SNAPSHOT'

java {
	toolchain {
		languageVersion = JavaLanguageVersion.of(8) // Java 8로 수정
	}
}

configurations {
	compileOnly {
		extendsFrom annotationProcessor
	}
}

repositories {
	mavenCentral()
}

dependencies {
	// Spring Boot 2.7.x 표준 Web Starter
	implementation 'org.springframework.boot:spring-boot-starter-web'
	
	// MyBatis: Spring Boot 2.x와 호환되는 2.3.x 버전 유지
	implementation 'org.mybatis.spring.boot:mybatis-spring-boot-starter:2.3.2'
	
	// XML 데이터를 객체로 변환(역직렬화)하기 위한 핵심 라이브러리
    implementation 'com.fasterxml.jackson.dataformat:jackson-dataformat-xml'
    
    // FTP 의존성 추가
    implementation 'commons-net:commons-net:3.9.0'
	
	compileOnly 'org.projectlombok:lombok'
	runtimeOnly 'org.postgresql:postgresql'
	annotationProcessor 'org.projectlombok:lombok'
	
	testImplementation 'org.springframework.boot:spring-boot-starter-test'
	testImplementation 'org.mybatis.spring.boot:mybatis-spring-boot-starter-test:2.3.2'
}

tasks.named('test') {
	useJUnitPlatform()
}